-- ===========================================================================
-- Schemas
--
-- GENERATED by scripts/dump_redshift_demo.py from the live Redshift cluster.
-- Do not hand-edit: re-run the dump instead, or the restore will drift from
-- what the application was actually demoed against.
--
-- Generated: 2026-08-12T09:11:21+00:00
-- ===========================================================================

CREATE SCHEMA IF NOT EXISTS demo_fast_test;
CREATE SCHEMA IF NOT EXISTS demo_schema_test;
