-- ===========================================================================
-- Table DDL (DROP + CREATE)
--
-- GENERATED by scripts/dump_redshift_demo.py from the live Redshift cluster.
-- Do not hand-edit: re-run the dump instead, or the restore will drift from
-- what the application was actually demoed against.
--
-- Generated: 2026-08-12T09:11:21+00:00
-- ===========================================================================

-- ---------- demo_fast_test ----------

DROP TABLE IF EXISTS demo_fast_test.customers CASCADE;
CREATE TABLE demo_fast_test.customers (
    id integer NOT NULL ENCODE az64,
    name character varying(50) ENCODE lzo COLLATE case_sensitive,
    signup_year integer ENCODE az64
)
DISTSTYLE AUTO;

DROP TABLE IF EXISTS demo_fast_test.orders CASCADE;
CREATE TABLE demo_fast_test.orders (
    id integer NOT NULL ENCODE az64,
    customer_id integer ENCODE az64,
    amount integer ENCODE az64
)
DISTSTYLE AUTO;

DROP TABLE IF EXISTS demo_fast_test.payments CASCADE;
CREATE TABLE demo_fast_test.payments (
    payment_id integer NOT NULL ENCODE az64,
    order_id integer NOT NULL ENCODE az64,
    amount numeric(10,2) NOT NULL ENCODE az64,
    paid_on date NOT NULL ENCODE az64,
    payment_method character varying(20) NOT NULL ENCODE lzo COLLATE case_sensitive
)
DISTSTYLE AUTO;

DROP TABLE IF EXISTS demo_fast_test.products CASCADE;
CREATE TABLE demo_fast_test.products (
    product_id integer NOT NULL ENCODE az64,
    sku character varying(20) NOT NULL ENCODE lzo COLLATE case_sensitive,
    product_name character varying(60) NOT NULL ENCODE lzo COLLATE case_sensitive,
    unit_price numeric(10,2) NOT NULL ENCODE az64,
    in_stock boolean NOT NULL ENCODE raw
)
DISTSTYLE AUTO;

DROP TABLE IF EXISTS demo_fast_test.regions CASCADE;
CREATE TABLE demo_fast_test.regions (
    region_id integer NOT NULL ENCODE az64,
    region_name character varying(40) NOT NULL ENCODE lzo COLLATE case_sensitive,
    country character varying(40) NOT NULL ENCODE lzo COLLATE case_sensitive
)
DISTSTYLE AUTO;

-- ---------- demo_schema_test ----------

DROP TABLE IF EXISTS demo_schema_test.departments CASCADE;
CREATE TABLE demo_schema_test.departments (
    department_id integer NOT NULL ENCODE az64,
    department_name character varying(40) NOT NULL ENCODE lzo COLLATE case_sensitive,
    location character varying(40) NOT NULL ENCODE lzo COLLATE case_sensitive
)
DISTSTYLE AUTO;

DROP TABLE IF EXISTS demo_schema_test.employees CASCADE;
CREATE TABLE demo_schema_test.employees (
    employee_id integer NOT NULL ENCODE az64,
    full_name character varying(60) NOT NULL ENCODE lzo COLLATE case_sensitive,
    department_id integer NOT NULL ENCODE az64,
    hired_on date NOT NULL ENCODE az64,
    salary numeric(10,2) NOT NULL ENCODE az64
)
DISTSTYLE AUTO;
