-- ===========================================================================
-- Row data (INSERT)
--
-- GENERATED by scripts/dump_redshift_demo.py from the live Redshift cluster.
-- Do not hand-edit: re-run the dump instead, or the restore will drift from
-- what the application was actually demoed against.
--
-- Generated: 2026-08-12T09:11:21+00:00
-- ===========================================================================

-- ---------- demo_fast_test ----------

-- demo_fast_test.customers — 10 row(s)
INSERT INTO demo_fast_test.customers ("id", "name", "signup_year") VALUES
    (1, 'Customer_1', 2021),
    (2, 'Customer_2', 2022),
    (3, 'Customer_3', 2023),
    (4, 'Customer_4', 2024),
    (5, 'Customer_5', 2020),
    (6, 'Customer_6', 2021),
    (7, 'Customer_7', 2022),
    (8, 'Customer_8', 2023),
    (9, 'Customer_9', 2024),
    (10, 'Customer_10', 2020);

-- demo_fast_test.orders — 10 row(s)
INSERT INTO demo_fast_test.orders ("id", "customer_id", "amount") VALUES
    (1, 2, 100),
    (2, 3, 200),
    (3, 4, 300),
    (4, 5, 400),
    (5, 6, 500),
    (6, 7, 600),
    (7, 8, 700),
    (8, 9, 800),
    (9, 10, 900),
    (10, 1, 1000);

-- demo_fast_test.payments — 8 row(s)
INSERT INTO demo_fast_test.payments ("payment_id", "order_id", "amount", "paid_on", "payment_method") VALUES
    (5001, 1, 120.50, '2024-01-15', 'card'),
    (5002, 2, 89.99, '2024-01-22', 'bank_transfer'),
    (5003, 3, 249.00, '2024-02-03', 'card'),
    (5004, 4, 45.00, '2024-02-19', 'paypal'),
    (5005, 5, 310.75, '2024-03-07', 'card'),
    (5006, 6, 15.25, '2024-03-28', 'bank_transfer'),
    (5007, 7, 199.99, '2024-04-11', 'card'),
    (5008, 8, 62.40, '2024-04-30', 'paypal');

-- demo_fast_test.products — 6 row(s)
INSERT INTO demo_fast_test.products ("product_id", "sku", "product_name", "unit_price", "in_stock") VALUES
    (1, 'SKU-1001', 'Wireless Mouse', 25.99, TRUE),
    (2, 'SKU-1002', 'Mechanical Keyboard', 89.50, TRUE),
    (3, 'SKU-1003', '27in Monitor', 249.00, FALSE),
    (4, 'SKU-1004', 'USB-C Dock', 139.95, TRUE),
    (5, 'SKU-1005', 'Laptop Stand', 45.00, TRUE),
    (6, 'SKU-1006', 'Noise Cancelling Headset', 199.99, FALSE);

-- demo_fast_test.regions — 5 row(s)
INSERT INTO demo_fast_test.regions ("region_id", "region_name", "country") VALUES
    (1, 'North East', 'United States'),
    (2, 'West Coast', 'United States'),
    (3, 'Midlands', 'United Kingdom'),
    (4, 'Bavaria', 'Germany'),
    (5, 'South India', 'India');

-- ---------- demo_schema_test ----------

-- demo_schema_test.departments — 5 row(s)
INSERT INTO demo_schema_test.departments ("department_id", "department_name", "location") VALUES
    (10, 'Engineering', 'London'),
    (20, 'Finance', 'New York'),
    (30, 'Marketing', 'Berlin'),
    (40, 'Support', 'Bangalore'),
    (50, 'Operations', 'Toronto');

-- demo_schema_test.employees — 5 row(s)
INSERT INTO demo_schema_test.employees ("employee_id", "full_name", "department_id", "hired_on", "salary") VALUES
    (1, 'Amara Osei', 10, '2021-03-01', 82000.00),
    (2, 'Ravi Krishnan', 20, '2020-07-15', 74500.00),
    (3, 'Elena Petrova', 30, '2022-01-10', 68000.00),
    (4, 'Tom Whitfield', 40, '2023-05-22', 51000.00),
    (5, 'Mei Lin Chen', 50, '2019-11-04', 91000.00);
