-- ===========================================================================
-- Functions and stored procedures
--
-- GENERATED by scripts/dump_redshift_demo.py from the live Redshift cluster.
-- Do not hand-edit: re-run the dump instead, or the restore will drift from
-- what the application was actually demoed against.
--
-- Generated: 2026-08-12T09:11:21+00:00
-- ===========================================================================

-- ---------- demo_fast_test ----------

-- FUNCTION demo_fast_test.f_customer_tenure
CREATE OR REPLACE FUNCTION demo_fast_test.f_customer_tenure(signup_year integer)
RETURNS integer
STABLE
AS $$ SELECT CAST(DATE_PART(year, CURRENT_DATE) - $1 AS INTEGER) $$
LANGUAGE sql;

-- FUNCTION demo_fast_test.f_discounted_total
CREATE OR REPLACE FUNCTION demo_fast_test.f_discounted_total(amount double precision, pct double precision)
RETURNS double precision
STABLE
AS $$ SELECT $1 * (1 - $2 / 100.0) $$
LANGUAGE sql;

-- FUNCTION demo_fast_test.f_is_active
CREATE OR REPLACE FUNCTION demo_fast_test.f_is_active(signup_year integer)
RETURNS boolean
STABLE
AS $$ SELECT $1 >= 2022 $$
LANGUAGE sql;

-- FUNCTION demo_fast_test.f_revenue_score
CREATE OR REPLACE FUNCTION demo_fast_test.f_revenue_score(amount double precision)
RETURNS integer
STABLE
AS $$ SELECT CASE WHEN $1 < 1000 THEN 1 WHEN $1 < 100000 THEN 2 ELSE 3 END $$
LANGUAGE sql;

-- FUNCTION demo_fast_test.f_tenure_years
CREATE OR REPLACE FUNCTION demo_fast_test.f_tenure_years(signup_year integer)
RETURNS integer
STABLE
AS $$ SELECT 2026 - $1 $$
LANGUAGE sql;

-- PROCEDURE demo_fast_test.sp_top_customers
CREATE OR REPLACE PROCEDURE demo_fast_test.sp_top_customers(min_spend double precision)
 LANGUAGE plpgsql
AS $$
BEGIN
    DROP TABLE IF EXISTS demo_fast_test.top_customers;
    CREATE TABLE demo_fast_test.top_customers AS
    SELECT c.id            AS customer_id,
           c.name          AS customer_name,
           c.signup_year   AS signup_year,
           COUNT(o.id)     AS order_count,
           SUM(o.amount)   AS total_spend
    FROM demo_fast_test.customers c
    JOIN demo_fast_test.orders o ON o.customer_id = c.id
    GROUP BY c.id, c.name, c.signup_year
    HAVING SUM(o.amount) >= min_spend;
END;
$$;
