"""Dump the live Redshift demo schemas to re-runnable SQL files.

Why this exists
---------------
The Redshift cluster bills whenever it is not paused, and a paused cluster still
costs storage. Capturing the demo source estate as SQL makes the cluster
*disposable*: destroy it, recreate a fresh one before the demo, run one script,
and the source data the app reads is back exactly as it was.

This is a dump tool, not a fixture author. Everything it writes is read from the
live cluster — table DDL comes from `SHOW TABLE`, routine DDL from
`SHOW PROCEDURE` / the pg_proc reconstruction the app already uses, and every
INSERT is generated from real rows. Nothing here is hand-written, so the restore
cannot silently drift from what the demo was actually built against.

Run (with the cluster UP):

    backend/.venv/bin/python scripts/dump_redshift_demo.py

Writes scripts/redshift-demo/*.sql. Re-run any time the demo data changes.
"""

from __future__ import annotations

import datetime
import decimal
import re
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
BACKEND = ROOT / "backend"
sys.path.insert(0, str(BACKEND))

from dotenv import load_dotenv  # noqa: E402

load_dotenv(BACKEND / ".env")

from app.connectors import redshift as rs  # noqa: E402

OUT_DIR = ROOT / "scripts" / "redshift-demo"
SCHEMAS = ("demo_fast_test", "demo_schema_test")

HEADER = """-- ===========================================================================
-- {title}
--
-- GENERATED by scripts/dump_redshift_demo.py from the live Redshift cluster.
-- Do not hand-edit: re-run the dump instead, or the restore will drift from
-- what the application was actually demoed against.
--
-- Generated: {when}
-- ===========================================================================

"""


def sql_literal(v: object) -> str:
    """Render one Python value as a Redshift SQL literal.

    String quoting doubles embedded apostrophes rather than backslash-escaping:
    Redshift's default `standard_conforming_strings` treats a backslash as a
    literal character, so `\\'` would insert a backslash AND end the string.
    """
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "TRUE" if v else "FALSE"
    if isinstance(v, (int, float, decimal.Decimal)):
        return str(v)
    # datetime BEFORE date — datetime is a subclass of date, and only datetime
    # accepts the `sep` argument.
    if isinstance(v, datetime.datetime):
        return "'" + v.isoformat(sep=" ") + "'"
    if isinstance(v, (datetime.date, datetime.time)):
        return "'" + v.isoformat() + "'"
    return "'" + str(v).replace("'", "''") + "'"


def dump_tables(schema: str) -> tuple[list[str], list[str]]:
    """Return (ddl_statements, insert_statements) for every table in `schema`."""
    ddl: list[str] = []
    dml: list[str] = []

    for t in rs.list_tables(schema):
        if t.type == "view":
            # A view has no rows of its own and its body references other
            # objects; ordering it correctly is a separate problem. None of the
            # demo schemas currently contain one — flagged rather than guessed.
            print(f"  !! SKIPPING view {schema}.{t.name} — not handled by this dump")
            continue

        ddl.append(f"DROP TABLE IF EXISTS {schema}.{t.name} CASCADE;")
        ddl.append(rs.get_table_ddl(schema, t.name).rstrip().rstrip(";") + ";")
        ddl.append("")

        cols = rs.list_columns(schema, t.name)
        col_names = [c.name for c in cols]
        conn = rs._connect()
        try:
            cur = conn.cursor()
            quoted = ", ".join(f'"{c}"' for c in col_names)
            cur.execute(f'SELECT {quoted} FROM "{schema}"."{t.name}"')
            rows = cur.fetchall()
        finally:
            conn.close()

        dml.append(f"-- {schema}.{t.name} — {len(rows)} row(s)")
        if rows:
            col_list = ", ".join(f'"{c}"' for c in col_names)
            values = ",\n    ".join(
                "(" + ", ".join(sql_literal(v) for v in row) + ")" for row in rows
            )
            dml.append(f"INSERT INTO {schema}.{t.name} ({col_list}) VALUES\n    {values};")
        else:
            dml.append(f"-- (empty table — nothing to insert)")
        dml.append("")
        print(f"  {schema}.{t.name}: DDL + {len(rows)} row(s)")

    return ddl, dml


_VOLATILITY = {"i": "IMMUTABLE", "s": "STABLE", "v": "VOLATILE"}


def function_volatility(schema: str, name: str) -> str:
    """Read a function's real volatility from pg_proc.

    Redshift *requires* `IMMUTABLE | STABLE | VOLATILE` on CREATE FUNCTION
    (`42P13: create function must specify volatility attribute`), but the
    reconstruction in connectors/redshift.py does not emit one — it was written
    to feed the transpiler, which does not care. Restoring that DDL to a fresh
    cluster therefore fails on every function. Caught by actually replaying the
    dump into throwaway schemas; a parse-only check would have missed it.
    """
    conn = rs._connect()
    try:
        cur = conn.cursor()
        cur.execute(
            "SELECT p.provolatile FROM pg_proc p "
            "JOIN pg_namespace n ON n.oid = p.pronamespace "
            "WHERE n.nspname = %s AND p.proname = %s",
            (schema, name),
        )
        row = cur.fetchone()
    finally:
        conn.close()
    # VOLATILE is Redshift's own default, so it is the safe fallback.
    return _VOLATILITY.get(row[0] if row else None, "VOLATILE")


def add_volatility(ddl: str, volatility: str) -> str:
    """Insert the volatility clause between RETURNS ... and AS $$."""
    if re.search(r"\b(IMMUTABLE|STABLE|VOLATILE)\b", ddl):
        return ddl
    out, n = re.subn(r"\nAS\s+\$\$", f"\n{volatility}\nAS $$", ddl, count=1)
    if n == 0:
        # Shape we did not anticipate — say so rather than emit DDL that will
        # fail on restore with a confusing error.
        raise ValueError("could not locate 'AS $$' to insert the volatility clause")
    return out


def dump_routines(schema: str) -> list[str]:
    """Return CREATE statements for every function and procedure in `schema`."""
    out: list[str] = []
    for r in rs.list_routines(schema):
        try:
            if r.type == "PROCEDURE":
                body = rs.get_procedure_ddl(schema, r.name)
            else:
                body = add_volatility(
                    rs.get_function_ddl(schema, r.name),
                    function_volatility(schema, r.name),
                )
        except Exception as exc:  # noqa: BLE001 — report, never emit a fake body
            print(f"  !! FAILED {r.type} {schema}.{r.name}: {exc}")
            out.append(f"-- !! FAILED TO DUMP {r.type} {schema}.{r.name}: {exc}")
            out.append("")
            continue

        body = body.rstrip().rstrip(";")
        # Redshift's SHOW output is already CREATE OR REPLACE for procedures;
        # functions are reconstructed as CREATE OR REPLACE by the connector.
        out.append(f"-- {r.type} {schema}.{r.name}")
        out.append(body + ";")
        out.append("")
        print(f"  {schema}.{r.name} ({r.type})")
    return out


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    when = datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds")

    schema_sql = [f"CREATE SCHEMA IF NOT EXISTS {s};" for s in SCHEMAS]

    all_ddl: list[str] = []
    all_dml: list[str] = []
    all_routines: list[str] = []

    for s in SCHEMAS:
        print(f"\n== {s}")
        ddl, dml = dump_tables(s)
        all_ddl += [f"-- ---------- {s} ----------", ""] + ddl
        all_dml += [f"-- ---------- {s} ----------", ""] + dml
        routines = dump_routines(s)
        if routines:
            all_routines += [f"-- ---------- {s} ----------", ""] + routines

    files = {
        "01_schemas.sql": ("Schemas", schema_sql),
        "02_tables.sql": ("Table DDL (DROP + CREATE)", all_ddl),
        "03_data.sql": ("Row data (INSERT)", all_dml),
        "04_functions.sql": ("Functions and stored procedures", all_routines),
    }
    for fname, (title, lines) in files.items():
        text = HEADER.format(title=title, when=when) + "\n".join(lines).rstrip() + "\n"
        (OUT_DIR / fname).write_text(text, encoding="utf-8")
        print(f"\nwrote {fname} ({len(text)} bytes)")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
